"""
NidaanPath AI — app/services/escalation_packet.py
Generates the clinician escalation packet (HTML + PDF).
"""
from __future__ import annotations
from typing import Dict, Any, List
from datetime import datetime
import os


DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This document is generated by NidaanPath AI, "
    "a prototype diagnostic-process continuity system. "
    "It is NOT a diagnosis, prescription, or official medical record. "
    "All information is derived from synthetic demo documents. "
    "No real patient data is used. "
    "Clinician professional judgment supersedes any information in this packet."
)

SYNTHETIC_LABEL = "⚠ SYNTHETIC DEMO DOCUMENT — NOT FOR MEDICAL USE"


def build_clinician_packet(case: Any, documents: List[Any]) -> Dict[str, Any]:
    """
    Build a structured clinician escalation packet from case data.
    Returns a dict suitable for template rendering and PDF generation.
    """
    confirmed_docs = [d for d in documents if d.confirmed_by_user]
    extractions = [d.get_extraction() for d in confirmed_docs]

    # Timeline summary
    timeline = []
    for doc in sorted(confirmed_docs, key=lambda d: d.document_date or '9999'):
        timeline.append({
            'date': doc.document_date or 'Unknown',
            'type': doc.document_type or 'Document',
            'provider': doc.provider or 'Unknown',
            'filename': doc.original_filename,
        })

    # Collect all symptoms
    all_symptoms = []
    for ex in extractions:
        all_symptoms.extend(ex.get('symptoms', []))
    unique_symptoms = list(dict.fromkeys(all_symptoms))

    # Tests ordered vs completed
    tests_ordered = []
    tests_completed = []
    for ex in extractions:
        tests_ordered.extend(ex.get('tests_ordered', []))
        tests_completed.extend(ex.get('tests_completed', []))

    # Referrals
    referrals_issued = []
    specialist_notes = []
    for ex in extractions:
        if ex.get('referral_specialty'):
            referrals_issued.append(ex['referral_specialty'])
        if ex.get('document_type') == 'specialist_consultation_note':
            specialist_notes.append(ex.get('provider', 'Unknown specialist'))

    # Medications
    all_meds = []
    for ex in extractions:
        all_meds.extend(ex.get('medication_mentions', []))
    unique_meds = list(dict.fromkeys(all_meds))

    # Unreviewed results
    unreviewed = []
    for ex in extractions:
        if ex.get('result_review_status') == 'not_reviewed':
            unreviewed.extend(ex.get('tests_completed', []))

    # Uncertainties
    all_uncertain = []
    for ex in extractions:
        all_uncertain.extend(ex.get('uncertain_fields', []))

    # Remaining gaps
    remaining_gaps = case.get_remaining_gaps() if hasattr(case, 'get_remaining_gaps') else []
    resolved_gaps = case.get_resolved_gaps() if hasattr(case, 'get_resolved_gaps') else []

    # Clinician questions (Safety Gate 3)
    clinician_questions = [
        "Have the existing laboratory reports (CBC and fasting glucose) been reviewed together?",
        "Which medication instruction is currently valid for this patient?",
        "What diagnostic uncertainty remains unresolved?",
        "Is the specialist follow-up (caloric test) pending?",
    ]
    if any(g.get('gap_id') == 'record_contradiction' for g in remaining_gaps):
        clinician_questions.insert(0,
            "⚠ CLINICIAN REVIEW REQUIRED: Conflicting medication instructions detected. "
            "Which is the current valid prescription?"
        )

    packet = {
        'generated_at': datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'),
        'case_code': case.case_code if hasattr(case, 'case_code') else 'DEMO',
        'synthetic_label': SYNTHETIC_LABEL,
        'disclaimer': DISCLAIMER,
        'patient_name': case.patient_name if hasattr(case, 'patient_name') else 'Arun Kumar',
        'main_concern': case.main_concern or 'Persistent dizziness',
        'journey_state': case.journey_state if hasattr(case, 'journey_state') else 'Unknown',
        'symptom_duration': case.symptom_duration or 'Approximately 2 months',
        'persistent_symptoms': unique_symptoms,
        'timeline': timeline,
        'tests_ordered': list(dict.fromkeys(tests_ordered)),
        'tests_completed': list(dict.fromkeys(tests_completed)),
        'unreviewed_results': list(dict.fromkeys(unreviewed)),
        'referrals_issued': list(dict.fromkeys(referrals_issued)),
        'specialist_notes': specialist_notes,
        'medication_mentions': unique_meds,
        'uncertain_fields': list(dict.fromkeys(all_uncertain)),
        'remaining_gaps': remaining_gaps,
        'resolved_gaps': resolved_gaps,
        'clinician_questions': clinician_questions,
        'total_documents': len(documents),
        'confirmed_documents': len(confirmed_docs),
    }
    return packet


def generate_pdf_packet(packet: Dict[str, Any], output_path: str) -> bool:
    """
    Generate a PDF clinician escalation packet using ReportLab.
    Returns True on success.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable
        )

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # Header
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor('#102A43'),
            spaceAfter=6,
        )
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=12,
        )
        heading2 = ParagraphStyle(
            'Heading2Custom',
            parent=styles['Heading2'],
            fontSize=13,
            textColor=colors.HexColor('#1D4ED8'),
            spaceBefore=14,
            spaceAfter=6,
        )
        body = ParagraphStyle(
            'BodyCustom',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
        )
        warning_style = ParagraphStyle(
            'Warning',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.HexColor('#B91C1C'),
            backColor=colors.HexColor('#FEF2F2'),
            borderPadding=6,
        )

        story.append(Paragraph("NidaanPath AI", title_style))
        story.append(Paragraph("Clinician Escalation Packet", subtitle_style))
        story.append(Paragraph(packet['synthetic_label'], warning_style))
        story.append(Spacer(1, 0.3 * cm))
        story.append(HRFlowable(color=colors.HexColor('#102A43'), thickness=1))
        story.append(Spacer(1, 0.3 * cm))

        # Case info table
        info_data = [
            ['Case Reference:', packet['case_code']],
            ['Generated:', packet['generated_at']],
            ['Patient:', packet['patient_name']],
            ['Main Concern:', packet['main_concern']],
            ['Journey State:', packet['journey_state']],
        ]
        info_table = Table(info_data, colWidths=[4 * cm, 13 * cm])
        info_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#102A43')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.5 * cm))

        # Timeline
        story.append(Paragraph("Chronological Timeline", heading2))
        for event in packet['timeline']:
            story.append(Paragraph(
                f"<b>{event['date']}</b> — {event['type']} | {event['provider']}",
                body
            ))
        story.append(Spacer(1, 0.3 * cm))

        # Tests
        story.append(Paragraph("Tests Ordered and Completed", heading2))
        story.append(Paragraph(
            f"Ordered: {', '.join(packet['tests_ordered']) or 'None'}",
            body
        ))
        story.append(Paragraph(
            f"Completed: {', '.join(packet['tests_completed']) or 'None'}",
            body
        ))
        if packet['unreviewed_results']:
            story.append(Paragraph(
                f"⚠ Results without documented review: "
                f"{', '.join(packet['unreviewed_results'])}",
                warning_style
            ))
        story.append(Spacer(1, 0.3 * cm))

        # Medications
        story.append(Paragraph("Medications Mentioned", heading2))
        for med in packet['medication_mentions']:
            story.append(Paragraph(f"• {med}", body))
        story.append(Spacer(1, 0.3 * cm))

        # Unresolved gaps
        story.append(Paragraph("Remaining Process Gaps", heading2))
        for gap in packet['remaining_gaps']:
            story.append(Paragraph(
                f"⚠ {gap.get('label', '')}: {gap.get('description', '')}",
                body
            ))
        story.append(Spacer(1, 0.3 * cm))

        # Clinician questions
        story.append(Paragraph("Questions for Clinician Review", heading2))
        for q in packet['clinician_questions']:
            story.append(Paragraph(f"→ {q}", body))
        story.append(Spacer(1, 0.5 * cm))

        # Disclaimer
        story.append(HRFlowable(color=colors.grey, thickness=0.5))
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph(packet['disclaimer'], ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            leading=12,
        )))

        doc.build(story)
        return True

    except Exception as e:
        print(f"[PDF generation error] {e}")
        return False
